language: java
cache:
  directories:
    - .docker
    - .autoconf
    - $HOME/.m2
services:
  - docker
jdk:
  - openjdk11
branches:
  only:
    - master
    - develop
    - /^hotfix\/.*$/
before_install:
  - docker-compose -f src/test/docker/elasticsearch-7-standalone.yml up -d
  - mkdir -p ~/.m2; wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_maven_settings.xml
  - cd $TRAVIS_BUILD_DIR
script:
  - "[ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ] && mvn clean deploy || mvn clean install"
after_success:
  - mvn clean test jacoco:report coveralls:report
after_script:
  - docker-compose -f src/test/docker/elasticsearch-7-standalone.yml kill
env:
  global:
    - secure: Cz3CJDjuIm52LplBphLsQwNv055US4oxG51PgpJE6IYdta8KJxv04QwK+ytgb3eDNA6ec7XpGPuCaMnDXhpTTdMiluN0ATZY4dEkCIVTnHWGW0Fr0ydlwutkYx/kFUYIJwu9FueEPJYMYgPZ2LTxa6rrUATJ2U13N7R2ul3A5kQ=
    - secure: fLDJXNgi3H8PkGkquJZ3UdsdD1f99cJhbwFCv2PcaIaMyh29Y40EHIlCOmcfdYNEFa4kfOib2vj0e6u8VWDhSzJc+FzOPUU1bi7VzkWAWlQo8jPoq61VBELa+Gq/PayBvsZCN2lqE3Rb92NbyN9D/4rsRWRkKan/MZ/2KZGlK8U=
